env:
  local:
    API_BASE_URL: https://jsonplaceholder.typicode.com/
    API_INPUT_DIR: resources/input

    DB_CONN: DRIVER={Microsoft Access Driver (*.mdb)};DBQ=resources\TestConn.mdb;
    COSMOSDB_URL: NOT_SUPPORTED
    COSMOSDB_COLL_PATH: NOT_SUPPORTED

    BID_FILES_DIR: resources/Bids
    STORAGE_ACCOUNT: NOT_SUPPORTED
    STORAGE_LOCATION: NOT_SUPPORTED

    FTP_HOST: ftp.aao.gov.au
    FTP_PORT: 21
    FTP_LOCAL_EXPORT_DIR: NOT_SUPPORTED
    FTP_LOCAL_IMPORT_DIR: NOT_SUPPORTED
    FTP_REMOTE_EXPORT_DIR: NOT_SUPPORTED
    FTP_REMOTE_IMPORT_DIR: lib_thesaurus

