env:
  dev-local:
    API_BASE_URL: https://jsonplaceholder.typicode.com/

    DB_CONN: DRIVER={Microsoft Access Driver (*.mdb)};DBQ=resources\TestConn.mdb;
    DB_PREFIX: 'dbo.'

    COSMOSDB_URL: https://some-cosmos-server.azure.com:443
    COSMOSDB_COLL_PATH: dbs/some-db/colls/some-collection

    BID_FILES_DIR: resources/bids
    xxxBID_FILES_DIR: STORAGE_LOCATION=today

    STORAGE_ACCOUNT: azure-account-name
    xxxSTORAGE_LOCATION: azure-location-name
    STORAGE_LOCATION: NOT_SUPPORTED

    FTP_HOST: ftp.aao.gov.au
    FTP_PORT: 21
    FTP_REMOTE_DIR: pub


  tst-cloud:
